# Generated by Django 4.2.5 on 2023-12-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_post_image_remove_post_location_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='pics/default_post.jpg', upload_to='pics/docs/'),
        ),
    ]
